### ISSUE TITLE
No project license

### ISSUE THREAD

**Issue by walter-ind** [gulpjs/gulpjs.github.io#104]
Gulp is a very popular open source tool used by the developers. 

As I can see, there have been many pull requests till now along with some issues and forks, therefore it is necessary to officially authorise the developers to use and improve the code of this repository. Thus, the repository should have a valid license.

If you allow me, I will submit a PR which will add a license to this repository and will close this issue at the same time. Also, suggest me the <a href="https://choosealicense.com/" >appropriate</a> license which I should add. 

Thanks a lot!!

**Comment by walter-ind** [comment]
@phated please reply.

**Comment by phated** [comment]
A project doesn't need a license to contribute. The gulp website was originally based on a purchased theme so I don't even know what the license can/should be. I'm also very busy with my personal life so I don't have the time to look into it.

**Comment by walter-ind** [comment]
Sure..I will close the issue.
