### ISSUE TITLE
new site

### ISSUE THREAD

**Issue by contra** [gulpjs/gulpjs.github.io#11]
Plans:
- [x] Nice landing screen
- [ ] Example section with scrollspy
  - similar to http://goratchet.com/components/ but walking you through the sample gulpfile
- [ ] Proper documentation section
  - consolidate readmes from gulp, vinyl-fs, glob-watcher, glob-stream, and vinyl
- [x] New plugin search site

**Comment by aliceperez** [comment]
Hello gulp team,
I'm a designer and frontend dev and i love gulp.js but i think your website don't have enough information for beginners so i made a prototype for a new website. please check it and tell me what you think
Link: https://marvelapp.com/gj54hh

**Comment by contra** [comment]
@aliceperez That looks really nice! Could use a few tweaks but I like it overall. Want to send a PR when you have it ready and we can back-and-forth on it a little bit there?

**Comment by phated** [comment]
@aliceperez That looks awesome!

**Comment by aliceperez** [comment]
thank you @contra and @phated , i will be working on it and sending a PR as soon as i can.

**Comment by phated** [comment]
@aliceperez just wanted to follow up and see if you need help or anything.

**Comment by aliceperez** [comment]
@phated a friend is helping me, She is better with html and css. I'm just a designer...

**Comment by phated** [comment]
@aliceperez open source needs more designers, so I'm glad you found this issue.  Thanks for the response.  Let us know if you never need anything, we can reach out to the larger gulp community.

**Comment by aliceperez** [comment]
@phated If you have another open source project I would like to help and sorry for my english.....

**Comment by bdougie** [comment]
Out of curiosity is this still happening? I can get some SVGs created based on the mock @aliceperez. The current state of gulpjs.com seems like it could use those.

**Comment by phated** [comment]
@contra let's close this now that you've redone the site.  I'll open some individual issues for "nice to haves"
