### ISSUE TITLE
Plugins page: Deprecated packages

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#113]
On the plugins page, we should either show that a plugin is deprecated or we should remove them from the search.

Ref gulpjs/plugins#225

**Comment by phated** [comment]
@donghwipark I think we should continue to show the deprecated package, but add an icon or banner about deprecation with the deprecation message (you can see an example from npm at https://www.npmjs.com/package/6to5)

**Comment by donghwipark** [comment]
@phated I am thinking adding banner with deprecation message "This package has been deprecated". How is that? 
And if banner is ok I will make some example to check if it suits with the Gulp.js design.

**Comment by phated** [comment]
@donghwipark since we pull information from npm, we might have the actual deprecation message available in the data we receive. If we have the message, I'd like to display it.

Please post any images you have of the design! Thank you. 😄

**Comment by donghwipark** [comment]
![image](https://user-images.githubusercontent.com/35325234/89474598-09b8fe00-d7c1-11ea-8a1b-b0cb53c61c0d.png)
![image](https://user-images.githubusercontent.com/35325234/89474626-1b020a80-d7c1-11ea-86f4-1c0271dd8c73.png)
This two images are the desktop and mobile version of deprecate notification example. Please confirm. 

 Additionally the message should be the actual deprecation message from npm not the fixed "This package has been deprecated"?

**Comment by phated** [comment]
@donghwipark these designs look great! Have you researched if the deprecation message is available in the data we receive from npm's API?

**Comment by donghwipark** [comment]
@phated oh not yet that screenshot was taken from the google develper mode. I will check and if the deprecate message is included I will change to that one!!

**Comment by donghwipark** [comment]
@phated The problem is I cannot find the deprecated package example. I am checking response with console.log through plugin page. Can you give some example of deprecated package so check the response data again.

**Comment by phated** [comment]
@donghwipark https://www.npmjs.com/package/gulp-webpack

**Comment by phated** [comment]
@donghwipark based on our chat today, I found that npm search actually filters gulp-webpack (and probably all deprecated packages?) by default; however, if I add `is:unstable` and `not:unstable` to the query, it tricks the API into returning gulp-webpack (see https://registry.npmjs.com/-/v1/search?from=0&text=keywords:gulpplugin%20is:unstable%20not:unstable%20webpack&quality=0.5&popularity=1.0&maintenance=0.1)

If you add those 2 strings to the array at https://github.com/gulpjs/gulpjs.github.io/blob/source/src/pages/plugins/index.js#L151, gulp-webpack will start showing in the search results. I also noticed that the object contains the deprecated message (screenshot attached)!

<img width="934" alt="Screen Shot 2020-08-08 at 11 28 58 PM" src="https://user-images.githubusercontent.com/992373/89726398-0004e580-d9cf-11ea-8d24-81c75caac05f.png">

**Comment by donghwipark** [comment]
@phated Thank you for the guidelines. I will add the query if it is not yet modified and check the deprecated message. Will display the message below the default message "This package has been deprecated".

**Comment by donghwipark** [comment]
![image](https://user-images.githubusercontent.com/35325234/89744330-d5a64b80-dae6-11ea-8f15-c3ccbd5597e4.png)
I am trying to change the background color for the card same as I show you on the top. But couldn't find the card's style. It seems the layout css is somewhere out of the src folder.

**Comment by phated** [comment]
The `card` class is provided by Docusaurus' CSS Framework (called [Infima](https://facebookincubator.github.io/infima/)), but you can add another class at https://github.com/gulpjs/gulpjs.github.io/blob/d0c3bf316e75c9e115fef38e003bbee224754bf1/src/pages/plugins/index.js#L101

We use "CSS Modules", which means that styles for this component are in https://github.com/gulpjs/gulpjs.github.io/blob/d0c3bf316e75c9e115fef38e003bbee224754bf1/src/pages/plugins/plugins.module.scss and you can combine the classes using `classnames` (example at https://github.com/gulpjs/gulpjs.github.io/blob/d0c3bf316e75c9e115fef38e003bbee224754bf1/src/pages/plugins/index.js#L102)

**Comment by donghwipark** [comment]
@phated This will be the new design of the deprecated card
1. Desktop
![image](https://user-images.githubusercontent.com/35325234/89855991-f946c000-dbd2-11ea-91b9-187604ab7b60.png)
2. Mobile 
![image](https://user-images.githubusercontent.com/35325234/89856016-0f548080-dbd3-11ea-9d0c-968aee623129.png)

**Comment by phated** [comment]
@donghwipark I don't like how large that is, can you fit the message on the existing card instead of increasing the size?

**Comment by phated** [comment]
Ideally, deprecated plugins should not require more space than other plugins. We also don't need any of the other information, so you can remove keywords and description, etc.

**Comment by donghwipark** [comment]
1. I delete the keywords and description(card > body) in the deprecated card
2. Reduced the font size of messages
3. Need to confirm on background-color within all-cover or just the deprecate message part
    a. Desktop version(just the deprecate message part)
![image](https://user-images.githubusercontent.com/35325234/89913272-7eab8e00-dc2e-11ea-8652-3e636c486638.png)
    b. mobile version(just the deprecate message part)
![image](https://user-images.githubusercontent.com/35325234/89913353-96831200-dc2e-11ea-8d81-2fd297cb6db0.png)
    c. Desktop version(All part)
![image](https://user-images.githubusercontent.com/35325234/89913530-ccc09180-dc2e-11ea-87eb-ba63d68ccef1.png)
    d. Mobile version(All part)
![image](https://user-images.githubusercontent.com/35325234/89913590-db0ead80-dc2e-11ea-8d3c-e0e78bf0dfc7.png)

**Comment by phated** [comment]
@donghwipark I think it is still too big, let me show a recommendation instead.

**Comment by phated** [comment]
@donghwipark It should look more like this (please ignore my very poor photo editing skills):
![89913530-ccc09180-dc2e-11ea-87eb-ba63d68ccef1](https://user-images.githubusercontent.com/992373/89931070-8fbdb600-dbc0-11ea-8b4a-ef068365d2e4.png)

**Comment by donghwipark** [comment]
This is the modificated version with the photo above.
1. Desktop
![image](https://user-images.githubusercontent.com/35325234/90019970-1de18b80-dcea-11ea-8ad1-9ee5ddff751e.png)
2. Mobile
![image](https://user-images.githubusercontent.com/35325234/90019998-289c2080-dcea-11ea-9270-80d82325334d.png)

**Comment by phated** [comment]
Completed by #126 (I typo'd the commit message)
