### ISSUE TITLE
Docusaurus: Unable to upgrade to newer alphas

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#123]
There are some breaking changes in Docusaurus alpha releases and we aren't able to upgrade to them automatically.

Need to research what is breaking and get us updated.

**Comment by donghwipark** [comment]
1. Documentation in docusaurus for the reference: https://github.com/facebook/docusaurus/blob/master/CHANGELOG-2.x.md
2. Issue: If we try to increase the version number, our website breaks
3. Discord: https://discordapp.com/invite/docusaurus

**Comment by phated** [comment]
As noted in https://github.com/gulpjs/gulpjs.github.io/issues/129#issuecomment-714448231, we should remove the workaround for the styling on the copy button once we upgrade.

**Comment by donghwipark** [comment]
![image](https://user-images.githubusercontent.com/35325234/97450632-489cc100-1976-11eb-9a7e-8a07817b26a5.png)
Checked the actual problem and will proceed to debug this issue.

**Comment by donghwipark** [comment]
From the https://discord.com/channels/398180168688074762/584803742801723424
![image](https://user-images.githubusercontent.com/35325234/97562482-08e0e280-1a25-11eb-8f33-540aff5b9782.png)
![image](https://user-images.githubusercontent.com/35325234/97562575-2e6dec00-1a25-11eb-85e7-2e9c6bd5f449.png)

Narrow the issue to the docusaurus.config.js file. Fix the 4 files below and 'npm run start' worked.(Pull requested)
1. Plugins: With the explanation as written by Sebastien Lorber in the link isProd seems not valid and this is only using on building production, thus no need. Furthurmore no error after delete isProd
2. Theme color: modified them color config in accordance with docs file in docusaurus. Please confirm pull requests file
3. Navbar links parameter: links has been changed to items so modified, no error after change
4. Footer title is mandatory: Added title in the footer array 

With these four modification application starts running. Had issue after running, but this seems local error.
![image](https://user-images.githubusercontent.com/35325234/97563467-704b6200-1a26-11eb-9031-8284e8e592c4.png)

**Comment by phated** [comment]
Thanks for all your work on this @donghwipark!! Closed by #133
