### ISSUE TITLE
"Copy to clipboard" button can't be seen on code snippets

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#129]
I just noticed that if you hover on a code snippet, the "Copy" button appears but you can't really see it because of the dark background and black text. We should fix that styling.

**Comment by uplancer** [comment]
I did a quick fix #130 
but, I think updating docusaurus to v2.0.0-alpha.66 will fix the problem.

**Comment by phated** [comment]
Thanks! I'll make a note about that in our upgrade issue. The upgrade needs a bunch of care to do and no one has taken it on yet.

**Comment by phated** [comment]
Temporarily fixed by #130

**Comment by uplancer** [comment]
@phated My pleasure. btw this is my first ever contribution to the open source :smiling_face_with_three_hearts: 
Yes, I tried to upgrade, but it's a bit challenging :smile:

I will try to upgrade to the latest version :crossed_fingers:

**Comment by phated** [comment]
@uplancer Oh cool! I'm glad we has something you could work on; you did great work!

Please let me know on the upgrade issue if you need any guidance. I haven't tried upgrading and I know they changed a lot, but I have spent a lot of time looking at Docusaurus.
