### ISSUE TITLE
Wrong module syntax on gulpjs.com /  Named export 'dest' not found.

### ISSUE THREAD

**Issue by Sebi2020** [gulpjs/gulpjs.github.io#137]
### What actually happened?
[gulpjs.com](https://gulpjs.com/) shows example, which do not work, cause gulp is a CommonJS module, but the examples use ES-Module Syntax:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/1862664/174136404-e8372738-1619-4ef9-a6d8-d9d4b501462d.png">

Which causes the following error:
```
import {src, dest} from 'gulp';
             ^^^^
SyntaxError: Named export 'dest' not found. The requested module 'gulp' is a CommonJS module, which may not support all module.exports as named exports.
```

**Comment by Sebi2020** [comment]
@phated shouldn't this be mentioned on the page? The getting started did not even mention that there is an esm module. It's really confusing if you mix different import styles on the pages.

**Comment by phated** [comment]
No, these are just flashy examples and not something you should be used as "getting started". There's a giant menu button to the getting started guide.

**Comment by bronzehedwick** [comment]
Got hit with this as well. Sorry to hear this won't be fixed.
