### ISSUE TITLE
Docusaurus v2 has been released!

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#147]
https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0

We should upgrade to the stable version, as they say they are going to follow semver closely with the stable versions.

@donghwipark I know we never finished #136 but perhaps we should complete both together. Would you be able to take this on?

**Comment by ghost** [comment]
@phated yes sure I will start to look into it

**Comment by ghost** [comment]
@phated I am trying to upgrade docusaurus to 2.4.1 but appId is required. Seems appId is provided through owners email and can you share the appId?

https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration

**Comment by phated** [comment]
@donghwipark it is great to hear from you!

Our new information for Algolia is:
App ID: HQ9BYTRO7N
Search API Key: e0f1bf55fa3f4fb5150c708638b02e22

**Comment by ghost** [comment]
@phated thank you after upgrade I am facing two issues. Cannot import useThemeContext, useHideableNavbar.
useThemeContext is solved but not the useHideableNavbar. I cannot find the documents so asked in discord so will update after the comments.

**Comment by ghost** [comment]
@phated can you have a look pull request https://github.com/gulpjs/gulpjs.github.io/pull/148  ? Upgrade has been done.

**Comment by ghost** [comment]
@phated I am looking for the changes from current web and future version 2 release web. The navbar is fixed on top but design seems a little bit change. Is this part need to be fixed too? I shared the image below so please let us know if fix is needed. 

Current nav bar
<img width="1440" alt="image" src="https://github.com/gulpjs/gulpjs.github.io/assets/35325234/24a6fe89-0593-4b22-ac53-e68917ac2ec1">

Future release nav bar
<img width="1440" alt="image" src="https://github.com/gulpjs/gulpjs.github.io/assets/35325234/bf540a75-f002-4b31-af0f-8e6cb9737903">

**Comment by phated** [comment]
The design needs to be exactly the same

**Comment by phated** [comment]
Completed by #149
