### ISSUE TITLE
vinyl adapters

### ISSUE THREAD

**Issue by contra** [gulpjs/gulpjs.github.io#17]
Need to pick a new npm keyword and add listing of these to the site

**Comment by Marak** [comment]
Has there been any updates on a vinyl adapter for dropbox?

As per: https://github.com/gulpjs/vinyl/issues/38, we are still looking for dropbox implementation.

All the user-land dropbox libraries look unmaintained, including the official one. :-\

I've previously contributed to https://github.com/sintaxi/dbox ( I added stream interfaces ), so I guess I'll try to update that library unless anyone has a better idea.

**Comment by contra** [comment]
@Marak Haven't seen anything with dropbox, feel free to tackle that w/ a blessing

**Comment by phated** [comment]
Moved to the "plugins" repo where this actually belongs.
