### ISSUE TITLE
No explanation of what Gulp actually is

### ISSUE THREAD

**Issue by rmlewisuk** [gulpjs/gulpjs.github.io#25]
There is nowhere on the website that says:
- what Gulp is
- what it does
- why someone might want to use it

This seems like it would be off putting to someone who perhaps hasn't used Gulp before. "Automate and enhance your workflow" is fine, but doesn't help newcomers.

Just a short explanation of what it is/does would be useful.

**Comment by heikki** [comment]
This PR could use some feedback -> https://github.com/gulpjs/gulpjs.github.io/pull/23

**Comment by heikki** [comment]
^ Bringing this in from the linked issue:

> I heard someone mention Gulp so I go to http://gulpjs.com to find out what it is. The only thing on the page is "Automate and enhance your workflow" (pretty high-level and non-specific) and then some vague features/qualities at the bottom if you scroll down (it mentions Node, so it must be some kind of automation thing for Node). I click the 'docs' link and it tells me how to install (install what? what is this?). I click the repo homepage and I get another hint -- "streaming build system". Ok still pretty vague but it relates to builds, I guess. Really making me work to figure out what this is!

> Maybe take a page from (what I'm assuming is a competing tool) Grunt (http://gruntjs.com/) and just throw a brief description ("The Javascript Task Runner") and a paragraph on the homepage describing what it is:

> "In one word: automation. The less work you have to do when performing repetitive tasks like minification, compilation, unit testing, linting, etc, the easier your job becomes. After you've configured it through a Gruntfile, a task runner can do most of that mundane work for you—and your team—with basically zero effort."

**Comment by contra** [comment]
Closing, I think the site is good as-is (recently updated). Any more information should go into docs, or possible other pages if we feel that it really needs to exist.
