### ISSUE TITLE
Docusaurus theme for the gulp website

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#31]
Hey website team!  We are in need of a [GitBook theme](http://toolchain.gitbook.com/themes/) for the documentation refresh.  More information at https://github.com/gulpjs/gulp/issues/1595

Anyone available to tackle this?

**Comment by matchai** [comment]
If I were to take on this issue, should I assume that #11 has been abandoned?
If a website redesign is around the corner, the theme should match the design of the upcoming site.

**Comment by phated** [comment]
I think that it falls into one of the items in that issue but I think the gulp red is so iconic that the website shouldn't stray from it.  The documentation will be gitbook and hosted on our domain, which is why we are in need of a custom theme.  Hope that helps.

**Comment by phated** [comment]
We might want to use https://github.com/GitbookIO/theme-api as a base.

**Comment by contra** [comment]
@matchai New site is up, same colors and fonts so no changes gitbook-wise.

**Comment by ansballard** [comment]
So as far as I can tell there's no current dev on this issue, is there anything I'm not seeing or can I try to dive in?

**Comment by contra** [comment]
@ansballard Go for it, don't think anyone is touching it right now

**Comment by phated** [comment]
There's nothing.  I think we want to work on the theme in a branch on this repo (once it's completed, we can figure out if we want to move it).

**Comment by ansballard** [comment]
Just a quick update. Had a few free hours yesterday so I got most of the way through a gitbook plugin that can pull down the `README.md` from https://github.com/isaacs/node-glob and split it out by any level headers. Haven't gotten to the point where I can inject the content from any section, but it looks pretty close, barring edge cases.

**Comment by phated** [comment]
@ansballard cool. That's not quite the theme but something we will be looking for (there's another issue open on the main repo for it).

**Comment by ansballard** [comment]
Oops, that's my bad, I thought the plugin fell under the theme. I'll post progress from here on in the main repo and get back here when I can get to the theme. But just to be clear, no progress on the actual theme as of yet, in case anyone else is watching for something to work on.

**Comment by Saturate** [comment]
Any work done on this yet? If not and I might throw my self at it.

**Comment by ansballard** [comment]
Nope, it's all you. I've been swamped with life so I haven't been able to get to it.

**Comment by phated** [comment]
@Saturate no work at all has been done (I did some initial research that I posted in the comments above).  It'd be awesome if you want to tackle this.

**Comment by Saturate** [comment]
Great, I'll look at it soonish when I have some free time.

It is correct that we want the GitBook docs to live here, and pull in content from the other repos?

**Comment by phated** [comment]
@Saturate my current thinking is that the theme and output will exist here and there will be some process to pull the markdown files from the main repository (don't worry about this part right now).

**Comment by Saturate** [comment]
Just a quick update, I did a lot of work with GitBook on my other (paid) projects. But haven't started on this issue yet, time is a constraint here, like all of us know :-)

But it's not forgotten, and after I'm settled in, I'll look at it (Just moved to Copenhagen).

**Comment by phated** [comment]
@Saturate No worries.  Documentation won't be a focus until the after the soft launch.  Though, we're definitely looking forward to your theme!

**Comment by SomethingNew71** [comment]
Hey is this currently being worked on?  I saw @Saturate was planning on tackling it but if he wasn't able to I can jump in and help out.  Would this ideally be hosted in the same place as the rest of the site? And would this be a direct replacement for the documentation currently in GitHub Markdown?

**Comment by phated** [comment]
@SomethingNew71 no one is working on it afaik, so feel free to work on it.  The current assumption is that the theme will live here and the gitbook will be generated from whatever documentation is gulp's main `docs/` directory.

**Comment by SomethingNew71** [comment]
10-4 I'll tinker with it give me a few days.  👍

**Comment by phated** [comment]
@SomethingNew71 still planning to work on this?

**Comment by SomethingNew71** [comment]
@phated yup got slammed at work and forgot to come back and pick it up. I'll work on it this coming week. 👍

**Comment by phated** [comment]
Perfect, thanks!  Ping me if you need anything, I plan to work on docs stuff this week.

**Comment by SomethingNew71** [comment]
Do you want to run the node app right from the docs folder 

eg. https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md

Or locally or do you want me to sign up for this on Gitbooks site? 

https://www.gitbook.com/pricing

![screen shot 2018-01-02 at 1 50 13 pm](https://user-images.githubusercontent.com/4572799/34495599-e968c6f4-efc3-11e7-8e12-10d17c90df60.png)

**Comment by phated** [comment]
@SomethingNew71 we'll do our own hosting from this repo (a docs/ folder makes sense) - btw, I'm super excited to have you working on this!

**Comment by SomethingNew71** [comment]
😄  Well, I am excited to be working on it!

**Comment by SomethingNew71** [comment]
@phated The first version has been pushed and a PR was created. Let me know your thoughts! :-)

**Comment by phated** [comment]
Completed by #78 - awesome work @SomethingNew71

**Comment by SomethingNew71** [comment]
Hurray! Thanks @phated
