### ISSUE TITLE
Some Gulp plugins don't appear in search results

### ISSUE THREAD

**Issue by revelt** [gulpjs/gulpjs.github.io#32]
Searching for `contrib` doesn't yield any results, for example, `gulp-contrib-clean` is not appearing in the search results, although it's appearing on npm [directly](https://www.npmjs.com/package/gulp-contrib-clean).

**Comment by leo** [comment]
The plugin you're talking about doesn't have the "gulpplugin" keyword in its `package.json`. Therefore it won't appear in the plugin list.

**Comment by revelt** [comment]
aha!

**Comment by phated** [comment]
Also note that "contrib" doesn't mean anything in the gulp ecosystem like it does in grunt's. That module is not recommended and you probably want to use the "del" module directly like we recommend in most of our docs.

**Comment by revelt** [comment]
thank you for advice!
