### ISSUE TITLE
"Built With Gulp" Badge

### ISSUE THREAD

**Issue by josephfusco** [gulpjs/gulpjs.github.io#34]
It would be nice to see gulp also have it's own "built with gulp" badge similar to what Grunt is doing and host via cdn? I see some projects use the custom https://shields.io implementation but there is no standardized badge.

See: http://gruntjs.com/built-with-grunt-badge

Design candidate: ![built with gulp](https://cloud.githubusercontent.com/assets/6676674/18641211/9f7765fe-7e69-11e6-9857-7df9500ed66c.png)

SVG: https://www.dropbox.com/s/ug6q1oplcmoo1zk/builtwith.svg?dl=0

**Comment by phated** [comment]
I'm not really a fan of even more badges, especially when they are just for branding.

I'll leave this open for my more feedback.

**Comment by josephfusco** [comment]
@phated Understandable
