### ISSUE TITLE
Contribute Section

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#37]
It would be nice to have a "Support Us"/Contribute section on the homepage like @aliceperez's designs at https://marvelapp.com/gj54hh/screen/14587285

It would be nice to show off some of our supporters as well because we've been asked to link to companies that would back us.

**Comment by bdougie** [comment]
Perhaps the same way webpack.js.org has their page, not the same styling, but just the idea of it? They pull directly from the open collective API, I would love to tinker with it and see how it can be of use.

**Comment by bdougie** [comment]
I am going to approach this, this afternoon - Let me know if the marvel mock is good to work off of or if there are tweaks to be made:

<img width="1429" alt="screenshot 2017-01-06 09 59 29" src="https://cloud.githubusercontent.com/assets/5713670/21727590/e19ddc78-d3f6-11e6-96a1-7cec4acec386.png">

**Comment by phated** [comment]
@bdougie awesome, thanks!  I think that's a good place to start and we can expand on it later (to show current backers/sponsors, etc).

**Comment by contra** [comment]
@bdougie Mock content and idea was good, should use the primitives on the new site though as much as possible - fonts, font-sizes, grid, buttons, etc. is already defined.

**Comment by phated** [comment]
Completed by #47 - thanks @bdougie!!!!
