### ISSUE TITLE
Adopt the "getting started" flow from mockup?

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#38]
Would we want to adopt the "Getting Started" flow from @aliceperez's mockup (https://marvelapp.com/gj54hh/screen/14587285) instead of linking to the GitHub docs for Getting Started?

**Comment by ansballard** [comment]
I've been trying to find a way to get some CSS chops, so I'll take a stab at this based off the home page. Hopefully I come out with something serviceable =D

**Comment by ansballard** [comment]
So everything but the step-by-step section has been implemented. Do you all feel like the step-by-step is necessary since we have the CLI example at the top of the page along with the full gulpfile? If not this mockup looks done and this issue can be closed.

**Comment by contra** [comment]
@ansballard Yep, agreed

**Comment by phated** [comment]
I did really like the step-by-step design but I think there's a solid case for the simplification (and keeping it above the fold).
