### ISSUE TITLE
Adopt "What is Gulp" section?

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#39]
Should we adopt the "What is gulp" section from @aliceperez's mockups (https://marvelapp.com/gj54hh/screen/14587285)?

**Comment by phated** [comment]
Actually, ref #25

**Comment by dantesolis** [comment]
Hey guy has this been already claimed? If not could I work on it ?

**Comment by phated** [comment]
@dantesolis hasn't been claimed.  Feel free to work on it (following the linked design as a guide).

**Comment by dantesolis** [comment]
cool @phated I'm claiming it. Thanks

**Comment by dantesolis** [comment]
Hey guys  so this might be a silly question, but how do you guys run the site locally and can I divide the css into multiple files or is it better to stay with only one  main css file and/or use scss?   


Thanks

**Comment by phated** [comment]
Stick with a single CSS file and only use plain CSS (no preprocessors).  In the latest redesign, contra removed all build process.  You can "run" the site locally with a static file server (https://www.npmjs.com/package/st is a good one).

**Comment by contra** [comment]
@phated Or `open index.html` works just as well

**Comment by dantesolis** [comment]
Hey guys so anything I could contribute to here? Thanks

**Comment by contra** [comment]
Closing, I think the site is good as-is. Any more information should go into docs, or possible other pages if we feel that it really needs to exist.

**Comment by contra** [comment]
@phated I'm open to adding new sections/pages and accepting PRs but this ticket is for the old comp design we're not using. Should open a new ticket to make it friendlier for beginners.
