### ISSUE TITLE
Add gulp to the site?

### ISSUE THREAD

**Issue by ansballard** [gulpjs/gulpjs.github.io#44]
Just wanted to see if there was any interest in adding a basic build system before the site gets to built out. The single css file is already a little unwieldy for me, and it might be nice to enforce some linting as well. A happy little side-effect could be that any code examples on the site can be copied straight from the repo itself, keeping them at least somewhat relevant over time. Thoughts?

**Comment by phated** [comment]
Nope, contra removed a build process in the redesign. We might add one back way down the road.
