### ISSUE TITLE
Add readme explaining how to work on the site

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#45]
We've been receiving some questions on how to work on the site.  We should have a readme describing the workflow (non-build process, static site).  Ref https://github.com/gulpjs/gulpjs.github.io/issues/39#issuecomment-270990942 for the simplest explanation.

**Comment by contra** [comment]
@phated One thing to note is not writing custom CSS wherever possible, not touching primitives, etc.

Seeing a lot of PRs writing shitloads of custom CSS that doesn't match the rest of the site, overriding shit like `.col-4` globally, etc.

**Comment by ansballard** [comment]
https://github.com/bdougie/gulpjs.github.io/blob/code/README.md This seems like a good starting point. Needs the screenshot updated but it gives you a structure to build on.

**Comment by contra** [comment]
@ansballard Feel free to submit a PR - screenshot + "clone and open index.html" should be enough instruction

**Comment by phated** [comment]
That's the old readme, right?  The screenshot is wrong and stuff.  Needs a complete overhaul and probably should be done from scratch.

**Comment by dantesolis** [comment]
Hey could I work on this one? Thanks

**Comment by contra** [comment]
@dantesolis Feel free to work on it and send a PR!

**Comment by dantesolis** [comment]
oh fudge I think I took a bit too long solving this issue, @saturate already took care of this.

**Comment by Saturate** [comment]
Yeah @dantesolis if you snooze you lose ;-) but feel free to review it!
