### ISSUE TITLE
add something that explains the pipeline

### ISSUE THREAD

**Issue by contra** [gulpjs/gulpjs.github.io#53]
Need a animation/video that shows file transformation pipelines and looks snazzy. This is to explain what gulp is and how it works.

Example pipeline would be best with CSS/JS and show vendor prefixing and whatnot.

If it's too difficult to explain, we could also make a nice video (I can do this) with a voice over and graphics.

**Comment by yunusga** [comment]
Let me try. Is there any idea what that would look like?

**Comment by contra** [comment]
@yunusga Really just files going in (of different types), them changing as they go through different steps/plugins in the pipe, and either one bundle coming out or multiple files going out with different types. I made some of these as videos for talks I gave in the past but they weren't very good looking. It should be like, hey look at this sample code - here's what it really looks like visually.

**Comment by zekth** [comment]
The way you describe it is more like a "commercial" demonstration and not a technical one i feel. The homepage looks fine for me in an experiment developer way i mean. Maybe adding a tab "demo" or a panel could be an idea? By this way you can introduce best practices like manipulating dist folders etc.

**Comment by phated** [comment]
This is done! The animated diagram is live on the new website!
