### ISSUE TITLE
Getting a cert error from the link in the readme

### ISSUE THREAD

**Issue by ansballard** [gulpjs/gulpjs.github.io#64]
Looks like the first link in the readme is pointing to https://gulpjs.com, which gives a cert error. The link in the description and the first google result are both http. Not sure if this is something that never worked or if the cert has expired or what.

**Comment by phated** [comment]
Github doesn't properly support SSL for custom domains.  Feel free to send a PR to change the readme

**Comment by ansballard** [comment]
Done!

**Comment by phated** [comment]
Fixed by #65
