### ISSUE TITLE
Mobile responsive

### ISSUE THREAD

**Issue by maddhruv** [gulpjs/gulpjs.github.io#70]
The navigation bar is not responsive with small size devices!

**Comment by phated** [comment]
Feel free to submit a PR 😃

**Comment by Mist12345** [comment]
Shouldn't this issue and pr #72 be closed now too? I thought they were still open and was going to fix it then realized that #73 resolved it.

**Comment by phated** [comment]
@Mist12345 I haven't had a chance to review and cleanup anything on that PR (it's not been merged)
