### ISSUE TITLE
Adding boilerplate projects

### ISSUE THREAD

**Issue by zekth** [gulpjs/gulpjs.github.io#82]
After talking about the homepage of the projects and how to describe gulp i thougth it would be nice to provide some boilerplate projects for each versions. Like creating new repository like gulpjs/gulpjs-boilerplate having readme and folders for each versions and specifications described for each case. By the way it could be nice to introduce some new internal gulp plugins too.

I can write it easily. Let me know if you're.

**Comment by contra** [comment]
One of the reasons I made gulp was to get rid of boilerplate - if we have to make boilerplates then we did something wrong. The API is supposed to be so minimal that we don't need them.

**Comment by zekth** [comment]
I see what you mean and i totally agree, but as you know its really common on the web to copy paste and wait for everything to work by itself.
As boilerplates i was meaning examples and case explanation.

**Comment by phated** [comment]
I agree with contra's sentiment but I'd describe it as "gulp is meant to feel like snapping together building bricks while teaching node best practices".

We already have recipes and they are going to be prominently featured on the new docs website.
