### ISSUE TITLE
Add nofollow to sponsor links

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#83]

**Comment by zekth** [comment]
Would it be an idea to open in a blank target? like:
`<a href="#" target="_blank" rel="noopener, noreferrer, nofollow">foo</a>`

**Comment by phated** [comment]
I usually don't like target=blank because power users ctrl-click/middle-click things anyway when they want a new tab.  Fine with the other stuff though, I think.

**Comment by zekth** [comment]
I agree with you but depends on people, i'm kind of middle click mouse user but on the laptop i never use this feature.
"noopener, noreferrer" are used to avoid security issues with the target=_blank. So if we don't use this target no need to use those tags.
