### ISSUE TITLE
Remove trailing slashes from links in plugin list

### ISSUE THREAD

**Issue by unconfident** [gulpjs/gulpjs.github.io#84]
Didn't find where sources of `https://gulpjs.com/plugins/` page located so posting here instead.

NPM website has updated recently and now links containing a slash after package name do not resolve correctly, resulting in a 404 page. Compare: [with](https://www.npmjs.com/package/gulp-assets/), [without](https://www.npmjs.com/package/gulp-assets)

Code in question:

```html
<!--                                          this slash ↴ -->
<a ng-href="https://www.npmjs.com/package/{{plugin.name}}/" target="_blank" title="Install" class="title" ng-bind="plugin.name"></a>
```

**Comment by contra** [comment]
Wow, that is really crummy behavior for their website. My gut says they should fix it, but if you send a PR to remove the slash we can merge it.

**Comment by unconfident** [comment]
I don't think plugins page is a part of this repository, at least I wasn't able to find it.

> My gut says they should fix it

Yeah, I agree but knowing how it is, it will probably take them multiple years to do so. Maybe they iterate quicker on the website than they do on the cli tool though. I'm also not seeing a public repo with sources for their main website anywhere so maybe it's private

**Comment by unconfident** [comment]
Looks like they fixed it on their end, trailing slashes now removed with a redirect
