### ISSUE TITLE
Nicer icon for docusaurus website

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#98]
We're now featured on the Docusaurus website!  However, they are using our favicon and it's getting blown up pretty big.  We should create a proper sized icon and submit a patch to their website to use that one.

**Comment by mikeattara** [comment]
Hello @phated, may I take it up and work on it

**Comment by mikeattara** [comment]
I have converted the logo to svg which is recommended by the Docusaurus team

**Comment by phated** [comment]
This has been completed by @mikeattara - thanks!
